export { default as About } from './About'
export { default as Contact } from './Contact'
export { default as Home } from './Home'
export { default as Teachers } from './Teachers'
export { default as Login } from './Login'
export { default as Profile } from './Profile'
export { default as Landing } from './Landing'
export { default as Register } from './Register'